#!/bin/sh

POLYHEIGHT=24
WINDOWGAP=12

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding          $POLYHEIGHT
bspc config border_width         2
bspc config window_gap           $WINDOWGAP

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a '*' state=floating
bspc rule -a URxvt state=tiled

$HOME/.config/polybar/launch.sh
